---
Name: restfulserverroutes
After:
  - '#rootroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
   'api/v1/live': 'VersionedRestfulServer'
   'api/v1': 'RestfulServer'
   'api/v2//$ResourceName/$ResourceID/$RelationName': 'RestfulServer\ControllerV2'